<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ZONA" Id="{7bdec6a7-0f5c-4490-a44d-0b1ed5284ea4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ZONA

VAR_INPUT
END_VAR

VAR_OUTPUT
END_VAR

VAR
	libero : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ZONA">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>